project:
  type: book
  output-dir: docs

book:
  title: "Causal Inference"
  author: "Felipe Torres Raposo"
  date: "18/09/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - experiments.qmd
    - matching.qmd
    - iv.qmd
    - diff.qmd
    - panel.qmd
    - rdd.qmd
    - frdd.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: flatly
  pdf:
    documentclass: scrreprt

editor: visual

publish:
  gh-pages:
    branch: gh-pages
    dir: docs

